services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:17
    container_name: multiplayer-soccer-db
    environment: # Variáveis de ambiente para configuração do banco de dados, se não definidas, usam valores padrão
      POSTGRES_USER: ${DB_USER:-postgres} 
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-football_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports: # Mapeia a porta 5432 do container para a porta 5433 do host para evitar conflitos locais
      - "127.0.0.1:5433:5432"  # ✅ Apenas local (SSH tunnel), não exposto publicamente
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
      image: redis:7
      container_name: multiplayer-soccer-redis
      ports:
        - "127.0.0.1:6379:6379" # opcional, só se quiser acessar local
      volumes:
        - redis_data:/data

  app:
    image: multiplayer-soccer-app:latest
    container_name: multiplayer-soccer-app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-football_db}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      JWT_SECRET: ${JWT_SECRET:?JWT_SECRET deve ser definido no arquivo .env}
      PORT: 3000
    expose:
      - "3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started


  nginx:
    image: multiplayer-soccer-nginx:latest
    container_name: multiplayer-soccer-nginx
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres_data:
  redis_data:

