services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:17
    container_name: multiplayer-soccer-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: football_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: multiplayer-soccer-app:latest
    container_name: multiplayer-soccer-app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: football_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: seu_secret_super_seguro_mude_em_producao
      PORT: 3000
    expose:
      - "3000"
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: multiplayer-soccer-nginx:latest
    container_name: multiplayer-soccer-nginx
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres_data:

